### ISSUE TITLE
Лишние конвейеры

### ISSUE THREAD

**Issue by ddvlru** [OMGfox/ivk_test#1]
Попробуйте, пожалуйста, убрать два лишних конвейера и обойтись без `grep` и `awk`.

**Comment by OMGfox** [comment]
К сожалению никак не могу придумать более элегантный способ не используя grep. Ну разве что использовать ключ -executable в утилите "find" но тогда в подсчет будут попадать не только файлы ELF формата но и обычные скрипты. Все остальные мои варианты не избавляют от второго конвейера.

Тем не менее мне было бы очень любопытно на этот способ посмотреть и буду очень признателен за пример. Спасибо!

**Comment by OMGfox** [comment]
Спасибо за подсказки. Немного переписал код и сделал его читабельнее. Все-таки удалось избавился и от `awk` и `grep`.
